language: objective-c
osx_image: xcode7.1
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/KeyboardWrapper.xcworkspace -scheme KeyboardWrapper-Example -sdk iphonesimulator9.1 -destination 'platform=iOS Simulator,name=iPhone 5' ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
