language: objective-c
osx_image: xcode8
script:
- xcodebuild test -workspace Example/KeyboardWrapper.xcworkspace -scheme KeyboardWrapper-Example -sdk iphonesimulator10.0 -destination 'platform=iOS Simulator,name=iPhone 5'

after_success:
- pod lib lint --quick
