language: objective-c
osx_image: xcode9
script:
- xcodebuild test -workspace Example/KeyboardWrapper.xcworkspace -scheme KeyboardWrapper-Example -sdk iphonesimulator11.0 -destination 'platform=iOS Simulator,name=iPhone 7'

after_success:
- pod lib lint --quick
